### ISSUE TITLE
missing data fields on folio_inventory.item tables

### ISSUE THREAD

**Issue by sbeltaine** [metadb-project/metadb#64]
We are running Metadb v1.2.2. There are 3 LDP data fields from the inventory_items table that are not available in the equivalent folio_inventory.item table (including in the JSON data array) in Metadb. 

- last_check_in__date_time
- last_check_in__service_point_id
- last_check_in__staff_member_id

Can these tables be added to Metadb?

**Comment by nassibnassar** [comment]
Unlike LDP, Metadb has no knowledge of specific tables; it only knows what it receives from Kafka.

In this case the issue is that LDP extracts second-level JSON objects, while Metadb does not do this yet.  You can select them from `folio_inventory.item` using `jsonb_extract_path_text()`, for example, `jsonb_extract_path_text(jsonb, 'lastCheckIn', 'dateTime')`.
